<?php

namespace MDQ\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CritEditURepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritEditURepository extends EntityRepository
{
}
