<?php

namespace MDQ\QuestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Dom3Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dom3Repository extends EntityRepository
{
}
