<?php

namespace MDQ\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends EntityRepository
{
}
