<?php

namespace MDQ\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function recupNews()
	{
		$em=$this->getDoctrine()->getManager();
		$news=$em->createQueryBuilder()
				->select('n')
				->from('MDQAdminBundle:News', 'n')
				->orderBy('n.publication', 'DESC')
				->addOrderBy('n.id', 'DESC');						
		return $news->getQuery()->getResult();
	}
}
