parameters:
#    mdq_question.example.class: MDQ\QuestionBundle\Example

services:
#    mdq_question.example:
#        class: %mdq_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
