<?php

namespace MDQ\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedaillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedaillesRepository extends EntityRepository
{
}
