<?php

namespace MDQ\GeneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateReferenceRepository extends EntityRepository
{
}
