<?php

namespace MDQ\GeneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatsQuotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsQuotRepository extends EntityRepository
{
}
